name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "sixdaysnews"
database_id = "47162bb3-191a-41b0-a7bd-c7ebf60316cc"
